[tool.black]
include = '\.pyi?$'
line-length = 120
py36 = false
skip-string-normalization = true

[tool.isort]
default_section = 'THIRDPARTY'
force_grid_wrap = 0
include_trailing_comma = true
known_first_party = 'datadog_checks'
line_length = 120
multi_line_output = 3
use_parentheses = true
